'use client';

/**
 * TEMPORARY DEVELOPMENT TOOL — does not affect the live /facilities page.
 * Route: /facilities-coordinate-tool
 *
 * Usage:
 *  1. Choose "Click-to-Place" mode, pick a marker from the dropdown,
 *     then click the map to move that marker to the clicked position.
 *  2. Or switch to "Drag" mode and drag any marker directly.
 *  3. Click "Copy Coordinates JSON" and paste the x/y values into
 *     lib/facilities.ts to make them permanent.
 */

import { useState, useRef, useEffect, useCallback } from 'react';
import Image from 'next/image';
import { FACILITIES } from '@/lib/facilities';

/* ── Types ─────────────────────────────────────────────────────────────────── */
type Coord = { id: number; name: string; x: number; y: number };
type Mode  = 'click' | 'drag';

/* ── Sorted initial state from lib/facilities.ts ────────────────────────────── */
const INIT: Coord[] = [...FACILITIES]
  .sort((a, b) => a.id - b.id)
  .map(f => ({ id: f.id, name: f.name, x: f.x, y: f.y }));

/* ── Colours ──────────────────────────────────────────────────────────────── */
const C = {
  bg:        '#0d0d0c',
  surface:   '#111110',
  border:    '#252523',
  borderSel: '#3b82f6',
  text:      '#d4d4cc',
  dim:       '#555552',
  gold:      '#c8a97e',
  blue:      '#3b82f6',
  blueMid:   'rgba(96,165,250,0.9)',
  green:     '#16a34a',
} as const;

/* ── Helpers ──────────────────────────────────────────────────────────────── */
function pad(n: number) { return String(n).padStart(2, '0'); }
function fmt(n: number) { return n.toFixed(1); }

/* ─────────────────────────────────────────────────────────────────────────── */
export default function FacilitiesCoordinateTool() {
  const [coords,     setCoords]     = useState<Coord[]>(INIT);
  const [selectedId, setSelectedId] = useState<number>(1);
  const [mode,       setMode]       = useState<Mode>('click');
  const [copied,     setCopied]     = useState(false);

  const mapRef        = useRef<HTMLDivElement>(null);
  const draggingIdRef = useRef<number | null>(null);

  /* ── Coordinate math ─────────────────────────────────────────────────────── */
  const toPercent = useCallback((clientX: number, clientY: number) => {
    const r = mapRef.current?.getBoundingClientRect();
    if (!r) return null;
    const clamp = (v: number) => Math.max(0, Math.min(100, v));
    return {
      x: Math.round(clamp(((clientX - r.left)  / r.width)  * 100) * 10) / 10,
      y: Math.round(clamp(((clientY - r.top)   / r.height) * 100) * 10) / 10,
    };
  }, []);

  const move = useCallback((id: number, x: number, y: number) =>
    setCoords(prev => prev.map(c => c.id === id ? { ...c, x, y } : c)),
  []);

  /* ── Drag mode: global mouse listeners ──────────────────────────────────── */
  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      if (draggingIdRef.current === null) return;
      const p = toPercent(e.clientX, e.clientY);
      if (p) move(draggingIdRef.current, p.x, p.y);
    };
    const onUp = () => { draggingIdRef.current = null; };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup',   onUp);
    return () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup',   onUp);
    };
  }, [toPercent, move]);

  /* ── Marker: mousedown ───────────────────────────────────────────────────── */
  const onMarkerDown = useCallback((id: number, e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();  // ← prevents map onClick in click-to-place mode
    setSelectedId(id);
    if (mode === 'drag') draggingIdRef.current = id;
  }, [mode]);

  /* ── Map: click-to-place ─────────────────────────────────────────────────── */
  const onMapClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (mode !== 'click') return;
    const p = toPercent(e.clientX, e.clientY);
    if (p) move(selectedId, p.x, p.y);
  }, [mode, selectedId, toPercent, move]);

  /* ── JSON output ─────────────────────────────────────────────────────────── */
  const jsonOutput = coords
    .map(c => `  { id: ${String(c.id).padEnd(2)}, /* ${c.name.padEnd(24)} */ x: ${fmt(c.x).padStart(5)}, y: ${fmt(c.y).padStart(5)} },`)
    .join('\n');

  const handleCopy = () => {
    const text =
      `// ── Updated coordinates — paste x/y values into lib/facilities.ts ──\n` +
      `// Generated by /facilities-coordinate-tool\n[\n${jsonOutput}\n]`;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const sel = coords.find(c => c.id === selectedId)!;

  /* ── Render ──────────────────────────────────────────────────────────────── */
  return (
    <div style={{ minHeight: '100vh', background: C.bg, color: C.text, padding: '14px', fontFamily: 'ui-monospace, monospace', fontSize: '12px' }}>

      {/* ── Header ── */}
      <div style={{ marginBottom: '10px', borderBottom: `1px solid ${C.border}`, paddingBottom: '10px' }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: '10px', marginBottom: '4px' }}>
          <h1 style={{ fontSize: '13px', fontWeight: 'bold', color: C.gold, margin: 0 }}>
            Facilities Marker Coordinate Editor
          </h1>
          <span style={{ fontSize: '10px', color: C.dim }}>dev-only — does not affect /facilities</span>
        </div>
        <p style={{ margin: '0 0 10px', fontSize: '11px', color: C.dim }}>
          Drag each marker to the correct place, then copy the coordinates JSON.
        </p>

        {/* Controls row */}
        <div style={{ display: 'flex', gap: '7px', flexWrap: 'wrap', alignItems: 'center' }}>

          {/* Mode buttons */}
          {(['click', 'drag'] as Mode[]).map(m => (
            <button key={m} onClick={() => setMode(m)} style={{
              padding: '4px 12px', fontSize: '11px', borderRadius: '5px', cursor: 'pointer',
              background: mode === m ? C.blue : C.surface,
              border:     `1px solid ${mode === m ? C.blue : C.border}`,
              color:      '#fff',
            }}>
              {m === 'click' ? '⊕ Click-to-Place' : '⇔ Drag'}
            </button>
          ))}

          {/* Marker selector */}
          <select
            value={selectedId}
            onChange={e => setSelectedId(Number(e.target.value))}
            style={{
              padding: '4px 8px', fontSize: '11px', borderRadius: '5px',
              background: C.surface, border: `1px solid ${C.border}`, color: C.text,
              maxWidth: '230px',
            }}
          >
            {coords.map(c => (
              <option key={c.id} value={c.id}>
                {pad(c.id)} — {c.name}
              </option>
            ))}
          </select>

          {/* Copy button */}
          <button onClick={handleCopy} style={{
            padding: '4px 14px', fontSize: '11px', borderRadius: '5px', cursor: 'pointer',
            background: copied ? C.green : C.gold,
            border: 'none', color: copied ? '#fff' : '#0d0d0c', fontWeight: 'bold',
            marginLeft: 'auto',
          }}>
            {copied ? '✓ Copied!' : '⎘ Copy Coordinates JSON'}
          </button>
        </div>

        {/* Selected marker info bar */}
        <div style={{
          marginTop: '8px', padding: '5px 12px',
          background: C.surface, border: `1px solid ${C.borderSel}`, borderRadius: '5px',
          display: 'flex', gap: '14px', flexWrap: 'wrap', alignItems: 'center', fontSize: '11px',
        }}>
          <span style={{ color: C.gold, fontWeight: 'bold' }}>
            #{pad(sel.id)} {sel.name}
          </span>
          <span>x: <strong style={{ color: '#60a5fa' }}>{fmt(sel.x)}%</strong></span>
          <span>y: <strong style={{ color: '#60a5fa' }}>{fmt(sel.y)}%</strong></span>
          <span style={{ color: C.dim, fontSize: '10px' }}>
            {mode === 'click'
              ? '→ Click anywhere on the map to move this marker'
              : '→ Click and drag the numbered circle'}
          </span>
        </div>
      </div>

      {/* ── Map ── */}
      <div
        ref={mapRef}
        onClick={onMapClick}
        style={{
          position: 'relative',
          width: '100%',
          cursor: mode === 'click' ? 'crosshair' : 'default',
          borderRadius: '10px',
          overflow: 'hidden',
          border: `1px solid ${C.border}`,
          boxShadow: '0 6px 32px rgba(0,0,0,0.5)',
          userSelect: 'none',
        }}
      >
        {/* Base map image — 1536 × 658 px */}
        <Image
          src="/assets/parkland/facilities/facilities-3d-map-clean.png"
          alt="Facilities map — coordinate editor"
          width={1536}
          height={658}
          className="w-full h-auto block"
          priority
          draggable={false}
        />

        {/* Markers */}
        {coords.map(c => {
          const isSel = c.id === selectedId;
          const sz    = isSel ? 26 : 20;
          const fs    = c.id >= 10 ? '0.48rem' : '0.56rem';
          return (
            <div
              key={c.id}
              style={{
                position:  'absolute',
                left:      `${c.x}%`,
                top:       `${c.y}%`,
                transform: 'translate(-50%, -50%)',
                cursor:    mode === 'drag' ? 'grab' : 'pointer',
                zIndex:    isSel ? 20 : 10,
                userSelect: 'none',
              }}
              onMouseDown={e => onMarkerDown(c.id, e)}
              onClick={e => e.stopPropagation()} /* prevent map click bubbling */
            >
              {/* Tooltip (selected marker only) */}
              {isSel && (
                <div style={{
                  position:   'absolute',
                  bottom:     `${sz / 2 + 7}px`,
                  left:       '50%',
                  transform:  'translateX(-50%)',
                  background: 'rgba(0,0,0,0.92)',
                  border:     `1px solid ${C.borderSel}`,
                  borderRadius: '5px',
                  padding:    '3px 8px',
                  whiteSpace: 'nowrap',
                  fontSize:   '10px',
                  color:      '#fff',
                  pointerEvents: 'none',
                  boxShadow:  '0 2px 10px rgba(0,0,0,0.7)',
                  zIndex:     30,
                }}>
                  #{pad(c.id)} {c.name}&nbsp;&nbsp;
                  <span style={{ color: '#60a5fa' }}>{fmt(c.x)}, {fmt(c.y)}</span>
                </div>
              )}

              {/* Marker circle */}
              <div style={{
                width:    sz,
                height:   sz,
                borderRadius: '50%',
                background:   isSel ? C.blue : C.blueMid,
                border:   `${isSel ? 2 : 1.5}px solid ${isSel ? '#ffffff' : 'rgba(255,255,255,0.5)'}`,
                display:  'flex',
                alignItems:     'center',
                justifyContent: 'center',
                fontSize:   fs,
                fontWeight: 'bold',
                color:      '#fff',
                fontFamily: 'ui-monospace, monospace',
                boxShadow:  isSel
                  ? '0 0 0 3px rgba(59,130,246,0.35), 0 0 14px rgba(59,130,246,0.5)'
                  : '0 1px 4px rgba(0,0,0,0.45)',
                transition: 'all 120ms ease',
              }}>
                {c.id}
              </div>
            </div>
          );
        })}
      </div>

      {/* ── Coordinate table ── */}
      <div style={{ marginTop: '10px' }}>
        <div style={{ fontSize: '10px', color: C.dim, marginBottom: '5px' }}>
          All coordinates — click any row to select that marker
        </div>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(195px, 1fr))',
          gap: '3px',
        }}>
          {coords.map(c => (
            <div
              key={c.id}
              onClick={() => setSelectedId(c.id)}
              style={{
                padding: '4px 8px',
                background:   c.id === selectedId ? '#0e1f3a' : C.surface,
                border:       `1px solid ${c.id === selectedId ? C.borderSel : C.border}`,
                borderRadius: '4px',
                cursor:       'pointer',
                display:      'flex',
                gap:          '7px',
                alignItems:   'center',
                fontSize:     '11px',
              }}
            >
              {/* Mini circle */}
              <span style={{
                background:     c.id === selectedId ? C.blue : '#1e3a5f',
                color:          '#fff',
                borderRadius:   '50%',
                width:          '17px',
                height:         '17px',
                minWidth:       '17px',
                display:        'inline-flex',
                alignItems:     'center',
                justifyContent: 'center',
                fontSize:       '9px',
                fontWeight:     'bold',
              }}>
                {c.id}
              </span>

              {/* Name */}
              <span style={{
                color: c.id === selectedId ? '#c8deff' : '#aaa',
                flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              }}>
                {c.name}
              </span>

              {/* x, y */}
              <span style={{ color: '#60a5fa', whiteSpace: 'nowrap', fontSize: '10px' }}>
                {fmt(c.x)}, {fmt(c.y)}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* ── JSON output ── */}
      <div style={{ marginTop: '10px' }}>
        <div style={{ fontSize: '10px', color: C.dim, marginBottom: '5px' }}>
          Coordinates JSON — paste the x/y values into lib/facilities.ts, then remove this dev route
        </div>
        <pre style={{
          background:   '#0d1117',
          border:       `1px solid ${C.border}`,
          borderRadius: '8px',
          padding:      '10px 12px',
          fontSize:     '10px',
          color:        '#7ee787',
          overflowX:    'auto',
          maxHeight:    '260px',
          overflowY:    'auto',
          margin:       0,
          lineHeight:   1.7,
        }}>
          {jsonOutput}
        </pre>
      </div>

    </div>
  );
}
